import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
  icons: {
    icon: '/logo2.svg'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
